# Generated by Django 3.2.6 on 2021-08-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210826_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='club',
        ),
        migrations.AddField(
            model_name='athlete',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.club'),
        ),
    ]
