# Generated by Django 3.2.6 on 2021-10-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210916_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('place', models.IntegerField()),
                ('resultid', models.CharField(max_length=30)),
                ('agemin', models.IntegerField()),
                ('agemax', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(choices=[('APNEA', 'APNEA'), ('BACK', 'BACK'), ('BIFINS', 'BIFINS'), ('BREAST', 'BREAST'), ('FLY', 'FLY'), ('FREE', 'FREE'), ('IMMERSION', 'IMMERSION'), ('MEDLEY', 'MEDLEY'), ('SURFACE', 'SURFACE'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('event_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('eventid', models.CharField(max_length=30)),
                ('event_number', models.IntegerField()),
                ('event_order', models.IntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.enrollment')),
            ],
        ),
        migrations.RemoveField(
            model_name='meet',
            name='athleteclubs',
        ),
        migrations.AlterField(
            model_name='club',
            name='clubid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='nation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='meet',
            name='course',
            field=models.CharField(blank=True, choices=[('LCM', 'LCM'), ('SCM', 'SCM'), ('SCY', 'SCY'), ('SCY', 'SCY'), ('SCM16', 'SCM16'), ('SCM20', 'SCM20'), ('SCM33', 'SCM33'), ('SCY20', 'SCY20'), ('SCY27', 'SCY27'), ('SCY33', 'SCY33'), ('SCY36', 'SCY36'), ('OPEN', 'OPEN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meet',
            name='entrytype',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('INVITATION', 'INVITATION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meet',
            name='reservecount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='meet',
            name='startmethod',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meet',
            name='timing',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL3', 'MANUAL3'), ('MANUAL1', 'MANUAL1')], max_length=15),
        ),
        migrations.DeleteModel(
            name='AthleteClub',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meet'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='clubs',
            field=models.ManyToManyField(through='main.Enrollment', to='main.Club'),
        ),
        migrations.AddField(
            model_name='meet',
            name='athletes',
            field=models.ManyToManyField(through='main.Enrollment', to='main.Athlete'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='clubs',
            field=models.ManyToManyField(through='main.Enrollment', to='main.Club'),
        ),
    ]
