# Generated by Django 3.2.6 on 2021-10-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211006_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='eventid',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athleteid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='clubid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='nation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='meet',
            name='entrytype',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INVITATION', 'INVITATION')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('athlete', 'club', 'meet')},
        ),
    ]
