nations = ['AFG',
           'ALB',
           'ALG',
           'ASA',
           'AND',
           'ANG',
           'ANT',
           'ARG',
           'ARM',
           'ARU',
           'AUS',
           'AUT',
           'AZE',
           'BAH',
           'BRN',
           'BAN',
           'BAR',
           'BLR',
           'BEL',
           'BIZ',
           'BEN',
           'BER',
           'BHU',
           'BOL',
           'BIH',
           'BOT',
           'BRA',
           'IVB',
           'BRU',
           'BUL',
           'BUR',
           'BDI',
           'CAM',
           'CMR',
           'CAN',
           'CPV',
           'CAY',
           'CAF',
           'CHA',
           'CHI',
           'CHN',
           'TPE',
           'COL',
           'COM',
           'CGO',
           'COK',
           'CRC',
           'CRO',
           'CUB',
           'CYP',
           'CZE',
           'PRK',
           'COD',
           'DEN',
           'DJI',
           'DMA',
           'DOM',
           'ECU',
           'EGY',
           'ESA',
           'GEQ',
           'ERI',
           'EST',
           'ETH',
           'FAR',
           'FIJ',
           'FIN',
           'MKD',
           'FRA',
           'GAB',
           'GAM',
           'GEO',
           'GER',
           'GHA',
           'GIB',
           'GBR',
           'GRE',
           'GRN',
           'GUM',
           'GUA',
           'GUI',
           'GBS',
           'GUY',
           'HAI',
           'HON',
           'HKG',
           'HUN',
           'IRI',
           'ISL',
           'IND',
           'INA',
           'IRQ',
           'IRL',
           'ISR',
           'ITA',
           'CIV',
           'JAM',
           'JPN',
           'JOR',
           'KAZ',
           'KEN',
           'KIR',
           'KOR',
           'KUW',
           'KGZ',
           'LAO',
           'LAT',
           'LBN',
           'LES',
           'LBR',
           'LBA',
           'LIE',
           'LTU',
           'LUX',
           'MAC',
           'MAD',
           'MAW',
           'MAS',
           'MDV',
           'MLI',
           'MLT',
           'MHL',
           'MTN',
           'MRI',
           'MEX',
           'FSM',
           'MDA',
           'MON',
           'MNE',
           'MGL',
           'MAR',
           'MOZ',
           'MYA',
           'NAM',
           'NRU',
           'NEP',
           'NED',
           'AHO',
           'NZL',
           'NCA',
           'NIG',
           'NGR',
           'NMA',
           'NOR',
           'OMA',
           'PAK',
           'PLW',
           'PLE',
           'PAN',
           'PNG',
           'PAR',
           'PER',
           'PHI',
           'POL',
           'POR',
           'PUR',
           'QAT',
           'ROU',
           'RUS',
           'RWA',
           'STP',
           'LCA',
           'SAM',
           'SMR',
           'KSA',
           'SEN',
           'SRB',
           'SEY',
           'SLE',
           'SGP',
           'SVK',
           'SLO',
           'SOL',
           'SOM',
           'RSA',
           'ESP',
           'SRI',
           'SKN',
           'VIN',
           'SUD',
           'SUR',
           'SWZ',
           'SWE',
           'SUI',
           'SYR',
           'TAH',
           'TJK',
           'TAN',
           'THA',
           'TLS',
           'TOG',
           'TGA',
           'TRI',
           'TUN',
           'TUR',
           'TKM',
           'TUV',
           'UGA',
           'UKR',
           'UAE',
           'USA',
           'URU',
           'UZB',
           'VAN',
           'VEN',
           'VIE',
           'ISV',
           'YEM',
           'ZAM',
           'ZIM',
           'Afghanistan',
           'Albania',
           'Algeria',
           'American Samoa',
           'Andorra',
           'Angola',
           'Antigua & Barbuda',
           'Argentina',
           'Armenia',
           'Aruba',
           'Australia',
           'Austria',
           'Azerbaijan',
           'Bahamas',
           'Bahrain',
           'Bangladesh',
           'Barbados',
           'Belarus',
           'Belgium',
           'Belize',
           'Benin',
           'Bermuda',
           'Bhutan',
           'Bolivia',
           'Bosnia-Herzegovina',
           'Botswana',
           'Brazil',
           'British Virgin Is.',
           'Brunei',
           'Bulgaria',
           'Burkina Faso',
           'Burundi',
           'Cambodia',
           'Cameroon',
           'Canada',
           'Cape Verde',
           'Cayman Islands',
           'Central African Rep.',
           'Chad',
           'Chile',
           'China',
           'Chinese Taipei',
           'Colombia',
           'Comoros',
           'Congo',
           'Cook Islands',
           'Costa Rica',
           'Croatia',
           'Cuba',
           'Cyprus',
           'Czech Republic',
           'DPR Korea',
           'Dem. Rep. of  Congo',
           'Denmark',
           'Djibouti',
           'Dominica',
           'Dominican Republic',
           'Ecuador',
           'Egypt',
           'El Salvador',
           'Equatorial Guinea',
           'Eritrea',
           'Estonia',
           'Ethiopia',
           'Faroe Islands',
           'Fiji',
           'Finland',
           'Fr. Yug. Rep. Macedonia',
           'France',
           'Gabon',
           'Gambia',
           'Georgia',
           'Germany',
           'Ghana',
           'Gibraltar',
           'Great Britain',
           'Greece',
           'Grenada',
           'Guam',
           'Guatemala',
           'Guinea',
           'Guinea-Bissau',
           'Guyana',
           'Haiti',
           'Honduras',
           'Hong Kong',
           'Hungary',
           'I. R. Iran',
           'Iceland',
           'India',
           'Indonesia',
           'Iraq',
           'Ireland',
           'Israel',
           'Italy',
           'Ivory Coast',
           'Jamaica',
           'Japan',
           'Jordan',
           'Kazakhstan',
           'Kenya',
           'Kiribati',
           'Korea',
           'Kuwait',
           'Kyrgyzstan',
           'Laos PDR',
           'Latvia',
           'Lebanon',
           'Lesotho',
           'Liberia',
           'Libya',
           'Liechtenstein',
           'Lithuania',
           'Luxembourg',
           'Macau',
           'Madagascar',
           'Malawi',
           'Malaysia',
           'Maldives',
           'Mali',
           'Malta',
           'Marshall Islands',
           'Mauritania',
           'Mauritius',
           'Mexico',
           'Micronesia',
           'Moldova',
           'Monaco',
           'Montenegro',
           'Mongolia',
           'Morocco',
           'Mozambique',
           'Myanmar',
           'Namibia',
           'Nauru',
           'Nepal',
           'Netherlands',
           'Netherlands Antilles',
           'New Zealand',
           'Nicaragua',
           'Niger',
           'Nigeria',
           'Northern Mariana Islands',
           'Norway',
           'Oman',
           'Pakistan',
           'Palau',
           'Palestine',
           'Panama',
           'Papua New Guinea',
           'Paraguay',
           'Peru',
           'Philippines',
           'Poland',
           'Portugal',
           'Puerto Rico',
           'Qatar',
           'Romania',
           'Russia',
           'Rwanda',
           'S. Tome & Principe',
           'Saint Lucia',
           'Samoa',
           'San Marino',
           'Saudi Arabia',
           'Senegal',
           'Serbia',
           'Seychelles',
           'Sierra Leone',
           'Singapore',
           'Slovakia',
           'Slovenia',
           'Solomon Islands',
           'Somalia',
           'South Africa',
           'Spain',
           'Sri Lanka',
           'St. Kitts & Nevis',
           'St. Vincent & Grenadines',
           'Sudan',
           'Suriname',
           'Swaziland',
           'Sweden',
           'Switzerland',
           'Syria',
           'Tahiti',
           'Tajikistan',
           'Tanzania',
           'Thailand',
           'Timor-Leste',
           'Togo',
           'Tonga',
           'Trinidad &Tobago',
           'Tunisia',
           'Turkey',
           'Turkmenistan',
           'Tuvalu',
           'Uganda',
           'Ukraine',
           'United Arab Emirates',
           'United States',
           'Uruguay',
           'Uzbekistan',
           'Vanuatu',
           'Venezuela',
           'Vietnam',
           'Virgin Islands',
           'Yemen',
           'Zambia',
           'Zimbabwe',
           ]
